#pragma once

//From glfw3.h
#define APEX_MOUSE_BUTTON_1         0
#define APEX_MOUSE_BUTTON_2         1
#define APEX_MOUSE_BUTTON_3         2
#define APEX_MOUSE_BUTTON_4         3
#define APEX_MOUSE_BUTTON_5         4
#define APEX_MOUSE_BUTTON_6         5
#define APEX_MOUSE_BUTTON_7         6
#define APEX_MOUSE_BUTTON_8         7
#define APEX_MOUSE_BUTTON_LAST      APEX_MOUSE_BUTTON_8
#define APEX_MOUSE_BUTTON_LEFT      APEX_MOUSE_BUTTON_1
#define APEX_MOUSE_BUTTON_RIGHT     APEX_MOUSE_BUTTON_2
#define APEX_MOUSE_BUTTON_MIDDLE    APEX_MOUSE_BUTTON_3